// Lista pré-definida de segmentos oferecida no campo "Segmento" do cadastro
// self-service (ver SignupPage.tsx). A última opção é um "escape hatch": ao
// ser selecionada, o campo de segmento libera escrita livre em vez de ficar
// restrito a esta lista — ver OTHER_SEGMENT_OPTION.
export const OTHER_SEGMENT_OPTION = 'Outro (liberar escrita no input para cadastro do segmento)'

export const SEGMENTS: string[] = [
  'Salão de Beleza',
  'Cabeleireiro',
  'Barbearia',
  'Manicure',
  'Pedicure',
  'Nail Designer',
  'Alongamento de Unhas',
  'Podologia',
  'Designer de Sobrancelhas',
  'Brow Designer',
  'Lash Designer',
  'Extensão de Cílios',
  'Micropigmentação',
  'Maquiagem Profissional',
  'Maquiagem para Noivas',
  'Penteados',
  'Mega Hair',
  'Alongamento Capilar',
  'Colorista',
  'Escovaria',
  'Studio de Cabelo',
  'Studio de Unhas',
  'Studio de Noivas',
  'Dia da Noiva',
  'Consultoria de Imagem',
  'Personal Stylist',
  'Visagismo',
  'Clínica de Estética',
  'Centro de Estética',
  'Esteticista',
  'Depilação',
  'Depilação a Laser',
  'Bronzeamento',
  'Limpeza de Pele',
  'Tratamentos Faciais',
  'Tratamentos Corporais',
  'Massoterapia',
  'Drenagem Linfática',
  'Spa',
  'Day Spa',
  'Spa Urbano',
  'Harmonização Facial',
  'Procedimentos Estéticos',
  'Terapias Capilares',
  'Clínica de Emagrecimento',
  'Criolipólise',
  'Modelagem Corporal',
  'Odontologia',
  'Clínica Odontológica',
  'Consultório Odontológico',
  'Ortodontia',
  'Odontopediatria',
  'Implantodontia',
  'Periodontia',
  'Endodontia',
  'Prótese Dentária',
  'Harmonização Orofacial',
  'Odontologia Estética',
  'Clareamento Dental',
  'Clínica de Implantes',
  'Radiologia Odontológica',
  'Clínica Médica',
  'Consultório Médico',
  'Clínica Multidisciplinar',
  'Psicologia',
  'Nutrição',
  'Fisioterapia',
  'Fonoaudiologia',
  'Terapia Ocupacional',
  'Quiropraxia',
  'Acupuntura',
  'Ginecologia',
  'Dermatologia',
  'Cardiologia',
  'Pediatria',
  'Oftalmologia',
  'Ortopedia',
  'Endocrinologia',
  'Clínica de Saúde da Mulher',
  'Pilates',
  'Yoga',
  'Academia',
  'Personal Trainer',
  'Studio Fitness',
  'Crossfit',
  'Dança',
  'Massagem Terapêutica',
  'Terapias Integrativas',
  'Medicina Integrativa',
  'Spa Terapêutico',
  'Relaxamento e Bem-Estar',
  OTHER_SEGMENT_OPTION,
]
